Repository boostcampwm-2024/refactor-web07-Ask-It, pull requests merged in 2025-01, with the labels that each got.

#4 fix(fe): modify tailwind config file
  apps/client/tailwind.config.js
  apps/server/src/app.module.ts
  apps/server/src/chats/chats.service.spec.ts
  apps/server/src/chats/test-chats.mock.ts
  apps/server/src/questions/questions.service.spec.ts
  apps/server/src/questions/test-questions-service.mock.ts
  apps/server/src/replies/replies.service.spec.ts
  apps/server/src/replies/test-replies-service.mock.ts
  apps/server/src/sessions-auth/sessions-auth.service.spec.ts
  apps/server/src/sessions-auth/test-sessions-auth-service.mock.ts
  apps/server/src/sessions/sessions.service.spec.ts
  apps/server/src/sessions/test-sessions-service.mock.ts
Labels: Configuration, Fix

#3 fix: modify deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#5 fix: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Configuration

#7 refactor(fe): add loadSessionData utility for session management
  apps/client/src/features/session/index.ts
  apps/client/src/features/session/session.util.ts
  apps/client/src/routes/session/$sessionId/$questionId/index.tsx
  apps/client/src/routes/session/$sessionId/index.tsx
  apps/server/src/questions/questions.service.spec.ts
Labels: Refactor

#9 refactor(be): rbac
  apps/server/prisma/migrations/20250108080402_rbac/migration.sql
  apps/server/prisma/migrations/20250108081719_remove_is_host/migration.sql
  apps/server/prisma/migrations/20250109050756_role_permission/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema.prisma
  apps/server/src/chats/test-chats.mock.ts
  apps/server/src/common/roles/permissions.ts
  apps/server/src/common/roles/roles.ts
  apps/server/src/questions/questions.service.spec.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/test-questions-service.mock.ts
  apps/server/src/replies/replies.service.spec.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/test-replies-service.mock.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/sessions-auth.service.spec.ts
  apps/server/src/sessions-auth/sessions-auth.service.ts
  apps/server/src/sessions-auth/test-sessions-auth-service.mock.ts
  apps/server/src/sessions/sessions.service.spec.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/sessions/test-sessions-service.mock.ts
Labels: Refactor, Feature

#16 fix: modify deploy.yml
  .github/workflows/deploy.yml
Labels: Fix, Deploy-Server, Deploy-Socket

#17 fix: modify deploy.yml
  .github/workflows/deploy.yml
  apps/server/README.md
  apps/socket-server/README.md
Labels: Fix

#20 fix(fe): fix build error
  apps/client/src/features/session/session.util.ts
Labels: Fix

#22 refactor(fe): optimize state access
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/features/modal/modal.hook.tsx
  apps/client/src/features/socket/socket.context.tsx
  apps/client/src/routes/session/$sessionId/index.tsx
Labels: Refactor

#24 refactor(fe): use useShallow access for improved performance
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/SessionParticipantsModal.tsx
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/features/session/session.util.ts
  apps/client/src/features/socket/socket.context.tsx
  apps/client/src/pages/HomePage.tsx
Labels: Refactor

#28 feat(be): docker
  .github/workflows/deploy.yml
  apps/server/.dockerignore
  apps/server/Dockerfile
  apps/socket-server/.dockerignore
  apps/socket-server/Dockerfile
Labels: Refactor

#29 fix(be): update Dockerfiles
  apps/server/Dockerfile
  apps/socket-server/Dockerfile
Labels: Configuration, Fix

#30 fix: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Configuration, Fix

#32 fix(fe): refactor authentication checks to use accessToken
  apps/client/src/components/Header.tsx
  apps/client/src/features/auth/auth.store.ts
  apps/client/src/features/session/session.util.ts
  apps/client/src/pages/HomePage.tsx
  apps/client/src/routes/index.tsx
  apps/client/src/routes/my.tsx
Labels: Bug, Fix

#36 refactor(fe): improve readability
  apps/client/.eslintrc.json
  apps/client/eslint.config.js
  apps/client/package.json
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/DeleteConfirmModal.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/components/modal/Participant.tsx
  apps/client/src/components/modal/SessionParticipantsModal.tsx
  apps/client/src/components/modal/SessionTerminateModal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionDivider.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/QuestionSection.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/auth/validation/validation-status.util.ts
  apps/client/src/features/modal/Background.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/tsconfig.app.json
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: Refactor

#44 refactor(be): replace in-memory refresh token with redis
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/common/redis.module.ts
  apps/server/src/main.ts
Labels: Refactor

#42 refactor(fe): optimize QuestionList, QuestionSection rendering performance
  apps/client/src/shared/model/deep-equal/deep-equal.ts
  apps/client/src/shared/model/deep-equal/index.ts
  apps/client/src/widgets/question-list/ui/QuestionList.tsx
  apps/client/src/widgets/question-list/ui/QuestionSection.tsx
Labels: Refactor

#45 fix(be): fix login error
  apps/server/src/auth/auth.controller.ts
Labels: Fix

#46 release: 1.0.1
  package.json
Labels: Release

#48 refactor(fe): split QuestionItem, ReplyItem components into multiple files
  apps/client/src/widgets/question-list/model/useQuestionActions.ts
  apps/client/src/widgets/question-list/ui/QuestionActions.tsx
  apps/client/src/widgets/question-list/ui/QuestionBody.tsx
  apps/client/src/widgets/question-list/ui/QuestionDeleteButton.tsx
  apps/client/src/widgets/question-list/ui/QuestionEditButton.tsx
  apps/client/src/widgets/question-list/ui/QuestionItem.tsx
  apps/client/src/widgets/question-list/ui/QuestionLikeButton.tsx
  apps/client/src/widgets/question-list/ui/QuestionPinButton.tsx
  apps/client/src/widgets/question-list/ui/ReplyCountButton.tsx
  apps/client/src/widgets/reply-list/model/useReplyActions.ts
  apps/client/src/widgets/reply-list/ui/ReplyActions.tsx
  apps/client/src/widgets/reply-list/ui/ReplyBody.tsx
  apps/client/src/widgets/reply-list/ui/ReplyDeleteButton.tsx
  apps/client/src/widgets/reply-list/ui/ReplyEditButton.tsx
  apps/client/src/widgets/reply-list/ui/ReplyHeader.tsx
  apps/client/src/widgets/reply-list/ui/ReplyItem.tsx
  apps/client/src/widgets/reply-list/ui/ReplyLikeButton.tsx
Labels: Refactor

#50 feat(fe): add skeleton UI
  apps/client/src/pages/session/ui/QuestionReplyPage.tsx
  apps/client/src/pages/session/ui/SessionPage.tsx
  apps/client/src/routes/session/route.tsx
  apps/client/src/widgets/chatting-list/ChattingListSkeletonUI.tsx
  apps/client/src/widgets/chatting-list/index.ts
  apps/client/src/widgets/question-list/index.ts
  apps/client/src/widgets/question-list/ui/QuestionListSkeletonUI.tsx
  apps/client/src/widgets/reply-list/index.ts
  apps/client/src/widgets/reply-list/ui/ReplyListSkeletonUI.tsx
Labels: Feature

#53 docs: update system architecture
  README.md
Labels: Documentation
