Repository boostcampwm-2024/refactor-web07-Ask-It, pull requests merged in 2025-02, with the labels that each got.

#58 feat(be): ai question enhancement
  apps/server/package.json
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.module.ts
  apps/server/src/ai/ai.service.spec.ts
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/dto/improve-question.dto.ts
  apps/server/src/ai/promt.constant.ts
  apps/server/src/ai/swagger/improve-question.swagger.ts
  apps/server/src/app.module.ts
  apps/server/tsconfig.json
Labels: Feature

#57 fix(fe): modify modal UI that create question and reply
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/QuestionContentEditor.tsx
  apps/client/src/features/create-update-question/ui/QuestionModalFooter.tsx
  apps/client/src/features/create-update-question/ui/QuestionModalHeader.tsx
  apps/client/src/features/create-update-reply/model/reply-modal.type.ts
  apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
  apps/client/src/features/create-update-reply/ui/QuestionPreview.tsx
  apps/client/src/features/create-update-reply/ui/ReplyContentEditor.tsx
  apps/client/src/features/create-update-reply/ui/ReplyContentView.tsx
  apps/client/src/features/create-update-reply/ui/ReplyModalFooter.tsx
  apps/client/src/features/create-update-reply/ui/ReplyModalHeader.tsx
  apps/client/src/shared/ui/modal/useModal.tsx
Labels: Fix

#63 refactor:(be) update prompt content
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/promt.constant.ts
Labels: Refactor

#64 feat(fe): Integrate question improvement API and enhance question/answer writing UI
  apps/client/src/entities/session/model/qna.util.ts
  apps/client/src/features/create-update-question/api/improve-question.api.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalSide.tsx
  apps/client/src/features/create-update-question/ui/QuestionContentView.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModalFooter.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModalSide.tsx
  apps/client/src/features/create-update-reply/ui/ReplyContentView.tsx
  apps/client/src/index.css
Labels: Refactor, Feature

#67 feat(be): implement question shortening feature
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/dto/shorten-question.dto.ts
  apps/server/src/ai/promt.constant.ts
  apps/server/src/ai/swagger/shorten-question.swagger.ts
  apps/server/src/auth/auth.service.ts
Labels: Feature

#69 feat(fe): integrate question shortening API
  apps/client/src/entities/session/model/qna.util.ts
  apps/client/src/features/create-update-question/api/shortening-question.api.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
Labels: Feature

#70 release: 1.1.0
  package.json
Labels: Release

#72 feat(be): create prompt result insertion API
  apps/server/prisma/migrations/20250210082219_prompt/migration.sql
  apps/server/prisma/migrations/20250210083749_update_history_column_name/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.module.ts
  apps/server/src/ai/ai.service.spec.ts
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/dto/create-history.dto.ts
  apps/server/src/ai/promt.constant.ts
  apps/server/src/ai/swagger/create-history.swagger.ts
Labels: Feature

#76 feat(be): implement ai request-restriction guard
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.module.ts
  apps/server/src/ai/guards/restrict-request.guard.ts
  apps/server/src/ai/guards/restrict-request.module.ts
  apps/server/src/common/redis.module.ts
Labels: Feature

#77 feat(fe): resend with requirements (UI), integrate the history API, and add a Popover component
  apps/client/src/features/ai-history/api/ai-history.ts
  apps/client/src/features/ai-history/index.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalSide.tsx
  apps/client/src/shared/ui/popover/Popover.tsx
  apps/client/src/shared/ui/popover/index.ts
Labels: Feature

#81 feat: add question retry API
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/dto/retry-question.dto.ts
  apps/server/src/ai/swagger/retry-question.swagger.ts
Labels: Feature

#83 feat(fe): integrate question improvement retry API, update Popover component, and remove question shortening feature
  apps/client/src/features/ai-history/api/ai-history.ts
  apps/client/src/features/create-update-question/api/improve-question-retry.api.ts
  apps/client/src/features/create-update-question/api/shortening-question.api.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/shared/ui/popover/Popover.tsx
  apps/client/src/widgets/question-list/ui/SessionSettingsDropdown.tsx
Labels: Feature

#87 fix(be): update history prompt type
  apps/server/src/ai/dto/create-history.dto.ts
Labels: Fix

#90 release: 1.2.0
  package.json
Labels: Release

#92 feat(be): add a classifier that determines whether question or reply have been improved
  .github/workflows/deploy.yml
  apps/classifier/.gitignore
  apps/classifier/Dockerfile
  apps/classifier/app.py
  apps/classifier/model.py
  apps/classifier/requirements.txt
  apps/classifier/schemas.py
Labels: Feature

#94 feat(be): add slang detection
  apps/classifier/app.py
  apps/classifier/model.py
  apps/classifier/schemas.py
Labels: Feature

#98 feat(be): stream response
  apps/server/package.json
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/ai.service.ts
  apps/server/src/ai/swagger/improve-question.swagger.ts
  apps/server/src/ai/swagger/improve-reply.swagger.ts
  pnpm-lock.yaml
Labels: Feature

#99 fix(be): fix swagger
  apps/server/src/ai/ai.controller.ts
  apps/server/src/ai/swagger/retry-question.swagger.ts
  apps/server/src/ai/swagger/retry-reply.swagger.ts
Labels: Fix

#101 feat(be): chatting filter
  apps/server/package.json
  apps/server/prisma/migrations/20250217090246_chatting_filter/migration.sql
  apps/server/prisma/migrations/20250217120000_update_abuse_to_enum/migration.sql
  apps/server/prisma/migrations/20250217161055_abuse_state_block/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/app.module.ts
  apps/server/src/chats/chats.module.ts
  apps/server/src/chats/chats.repository.ts
  apps/server/src/chats/chats.service.spec.ts
  apps/server/src/chats/chats.service.ts
  apps/server/src/chats/swagger/get-chats.swagger.ts
  apps/server/src/chats/test-chats.mock.ts
  apps/socket-server/src/chats/chats.service.spec.ts
  apps/socket-server/src/chats/test-chats.mock.ts
  apps/socket-server/src/socket/dto/abuse-chatting-event.dto.ts
  apps/socket-server/src/socket/socket.constant.ts
  apps/socket-server/src/socket/socket.controller.ts
  apps/socket-server/src/socket/socket.gateway.ts
  pnpm-lock.yaml
Labels: Feature

#104 fix(be): update socket server prisma schema
  apps/socket-server/prisma/schema.prisma
Labels: Fix

#96 feat(fe): add abuse chatting message filtering feature
  apps/client/src/entities/session/model/chatting.slice.ts
  apps/client/src/entities/session/model/chatting.type.ts
  apps/client/src/entities/session/ui/ChattingMessage.tsx
  apps/client/src/features/socket/model/socket.service.ts
  apps/client/src/features/socket/model/socket.type.ts
  apps/client/src/shared/ui/popover/Popover.tsx
  apps/client/src/widgets/chatting-list/ChattingList.tsx
  apps/client/tests/QnAPage.spec.ts
Labels: Feature

#103 feat(fe): add animated text component for AI features
  apps/client/src/features/create-update-question/api/improve-question-retry.api.ts
  apps/client/src/features/create-update-question/api/improve-question.api.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/AnimatedText.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/features/create-update-question/ui/QuestionContentView.tsx
  apps/client/src/features/create-update-reply/api/improve-reply-retry.api.ts
  apps/client/src/features/create-update-reply/api/improve-reply.api.ts
  apps/client/src/features/create-update-reply/model/useReplyWritingSupport.ts
  apps/client/src/features/create-update-reply/ui/AnimatedText.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
  apps/client/src/features/create-update-reply/ui/ReplyContentView.tsx
  apps/server/src/ai/ai.controller.ts
Labels: Feature

#105 fix(fe): adjust z-index of abuse message toggle button
  apps/client/src/widgets/chatting-list/ChattingList.tsx
Labels: Bug, Fix

#111 feat(be): improve abuse classifier model performance, implement input batch processing
  apps/classifier/app.py
  apps/classifier/model.py
  apps/classifier/schemas.py
Labels: Refactor, Feature

#112 fix(be): add history api in ai controller
  apps/server/src/ai/ai.controller.ts
Labels: Fix

#113 fix(be): fix ai controller code
  apps/server/src/ai/ai.controller.ts
Labels: Fix

#114 refactor(be): move chatting filter batch jobs from API server to Socket server
  apps/server/src/app.module.ts
  apps/server/src/chats/chats.module.ts
  apps/server/src/chats/chats.repository.ts
  apps/server/src/chats/chats.service.spec.ts
  apps/server/src/chats/chats.service.ts
  apps/server/src/socket/socket.constant.ts
  apps/server/src/socket/socket.controller.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.module.ts
  apps/socket-server/package.json
  apps/socket-server/src/app.module.ts
  apps/socket-server/src/chats/chat.event.ts
  apps/socket-server/src/chats/chats.controller.ts
  apps/socket-server/src/chats/chats.module.ts
  apps/socket-server/src/chats/chats.repository.ts
  apps/socket-server/src/chats/chats.service.spec.ts
  apps/socket-server/src/chats/chats.service.ts
  apps/socket-server/src/socket/socket.controller.ts
  apps/socket-server/src/socket/socket.gateway.ts
  pnpm-lock.yaml
Labels: Refactor

#116 release: 1.3.0
  package.json
Labels: Release

#118 fix(fe): add error handling and toast notifications for question and reply improvements
  apps/client/src/features/create-update-question/api/improve-question-retry.api.ts
  apps/client/src/features/create-update-question/api/improve-question.api.ts
  apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
  apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
  apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
  apps/client/src/features/create-update-reply/api/improve-reply-retry.api.ts
  apps/client/src/features/create-update-reply/api/improve-reply.api.ts
  apps/client/src/features/create-update-reply/model/useReplyWritingSupport.ts
  apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
  apps/client/src/features/create-update-reply/ui/CreateReplyModalFooter.tsx
Labels: Bug, Fix

#117 docs: update system architecture
  README.md
Labels: Documentation
